import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"

import { useBlobity } from "blobity"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pandai App | Privacy Policy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="">Pandai App</a>
        </h1>
        <Image src="/panda.svg" alt="P Logo" width={500} height={500} />
        <p className={styles.description}>Pandai App Privacy Policy</p>

        <div className={styles.grid}>
          <h2>KEBIJAKAN KAMI TERHADAP PRIVASI ANDA &rarr;</h2>
          <p className={styles.description}>
            Pandai App berkomitmen untuk melindungi privasi pengguna-penggunanya
            di Indonesia. Kebijakan privasi Pandai App ("Kebijakan Privasi")
            berlaku untuk semua informasi pribadi yang dikumpulkan oleh kami
            atau dikirimkan kepada kami, baik offline atau online, termasuk
            informasi pribadi yang dikumpulkan atau dikirimkan melalui situs
            kami ("Situs Web") dan setiap situs mobile, aplikasi, widget, dan
            fitur interaktif mobile lainnya (secara kolektif, "Aplikasi" kami),
            melalui halaman jejaring sosial resmi kami yang kami kendalikan
            ("Halaman Jejaring Sosial" kami) serta melalui pesan email dengan
            format HTML yang kami kirimkan kepada Anda (secara kolektif,
            termasuk Halaman Jejaring Sosial, Aplikasi dan Situs Web, "Situs").
            Apabila Anda tidak setuju dengan setiap ketentuan dalam Kebijakan
            Privasi ini, harap agar tidak menggunakan situs web kami atau
            mengirimkan informasi pribadi kepada kami.
          </p>
        </div>

        <div className={styles.grid}>
          <h2>INFORMASI PRIBADI &rarr;</h2>
          <p className={styles.description}>
            Informasi pribadi apa saja yang kami kumpulkan? “Informasi Pribadi"
            adalah informasi yang mengidentifikasikan Anda sebagai seorang
            individu, seperti: nama, nomor telepon, alamat email, gambar
            profile, Negara tempat tinggal, Alamat IP, Informasi demografi dan
            informasi lainnya yang disediakan oleh Anda
          </p>
        </div>

        <div className={styles.grid}>
          <p className={styles.description}>
            Bagaimana kami mengumpulkan informasi pribadi? Kami dan penyedia
            layanan kami dapat mengumpulkan Informasi Pribadi dengan cara-cara
            yang beragam, termasuk: Melalui Situs: Kami dapat mengumpulkan
            Informasi Pribadi melalui Situs, misalnya, saat Anda mendaftar
            sebagai user atau melakukan transaksi. Offline: Kami dapat
            mengumpulkan Informasi Pribadi dari Anda secara offline, seperti
            pada saat Anda menghubungi layanan pelanggan. Dari Sumber Lainnya:
            Kami dapat menerima Informasi Pribadi dari sumber lainnya, seperti
            melalui database publik; mitra pemasaran bersama; platform jejaring
            sosial dari orang-orang dengan siapa Anda berteman atau dengan cara
            lain terhubung pada platform jejaring sosial, serta dari pihak
            ketiga lainnya. Sebagai contoh, jika Anda memilih untuk
            menghubungkan akun jejaring sosial Anda ke akun situs web Anda,
            Informasi Pribadi tertentu dari akun jejaring sosial Anda akan
            terbagi dengan kami, yang dapat mencakup Informasi Pribadi yang
            merupakan bagian dari profil Anda atau profil teman Anda. Melalui
            browser atau perangkat: Informasi tertentu dikumpulkan oleh sebagian
            besar browser atau secara otomatis oleh perangkat Anda. Kami
            menggunakan informasi ini untuk tujuan statistikal dan juga untuk
            memastikan Situs kami berfungsi dengan baik. Melalui server berkas
            log: "Alamat IP" Anda adalah nomor yang secara otomatis diberikan
            pada komputer atau perangkat Anda yang Anda gunakan dengan Penyedia
            Layanan Internet (ISP) Anda. Alamat IP diidentifikasikan dan secara
            otomatis dimasukan dalam server berkas log kami setiap saat pengguna
            mengunjungi Situs, bersama dengan waktu kunjungan dan
            halaman-halaman yang dikunjungi. Mohon dicatat bahwa kami
            memperlakukan Alamat IP, log file server dan informasi terkait
            sebagai Informasi Lainnya, kecuali yang mengharuskan kami untuk
            melakukan sebaliknya berdasarkan hukum yang berlaku. Menggunakan
            cookies: Cookies memungkinkan server jaringan untuk mengalihkan data
            ke komputer atau perangkat untuk pencatatan dan tujuan lainnya.
            Apabila Anda tidak menginginkan informasi dikumpulkan melalui
            penggunaan cookies, terdapat prosedur singkat pada sebagian besar
            browser yang memungkinkan Anda untuk menolak penggunaan cookies.
            Untuk mempelajari lebih lanjut mengenai penggunaan cookies kami,
            Anda dapat melihat kebijakan cookies kami. Melalui penggunaan
            Aplikasi oleh Anda. Saat Anda mengunduh dan menggunakan suatu
            Aplikasi, kami dan penyedia layanan dapat melacak dan mengumpulkan
            penggunaan data Aplikasi, seperti tanggal dan waktu ketika Aplikasi
            dalam perangkat Anda mengakses server kami dan informasi dan file
            apa yang telah diunduh kan ke Aplikasi berdasarkan nomor perangkat
            Anda. Dari Anda: Informasi seperti tanggal lahir, gender dan kode
            pos, dan juga informasi lainnya, seperti sarana pilihan komunikasi
            Anda, dapat dikumpulkan pada saat Anda secara sukarela memberikan
            informasi ini. Lokasi Fisik: Kami dapat mengumpulkan lokasi fisik
            atas perangkat Anda. Dalam beberapa kasus, kami dapat menggunakan
            layanan pembayaran pihak ketiga untuk melakukan pembelian dan/atau
            mengumpulkan donasi melalui Situs. Dalam kasus-kasus tersebut,
            Informasi Pribadi Anda dapat dikumpulkan oleh pihak ketiga tersebut
            dan bukan oleh kami, dan hal tersebut merupakan subjek atas
            kebijakan privasi pihak ketiga, bukan daripada Kebijakan Privasi
            ini. Kita tidak memiliki kendali, dan tidak bertanggung jawab atas
            penggunaan atau pengungkapan oleh pihak ketiga atas Informasi
            Pribadi Anda. Bagaimana cara kami menggunakan Informasi Pribadi?
            Kami dapat menggunakan Informasi Pribadi: Untuk mengirimkan
            informasi administratif kepada Anda, sebagai contoh, informasi
            mengenai Situs dan perubahan ketentuan-ketentuan, syarat-syarat dan
            kebijakan-kebijakan kami. Karena informasi ini bisa saja penting
            untuk penggunaan Anda atas Situs, Anda tidak dapat memilih untuk
            tidak menerima komunikasi-komunikasi tersebut. Untuk melengkapi dan
            memenuhi transaksi Anda, sebagai contoh, untuk memproses pembayaran
            Anda, mengirimkan pesanan kepada Anda, berkomunikasi dengan Anda
            mengenai pembelian Anda dan menyediakan layanan pelanggan kepada
            Anda. Untuk memberikan Anda pembaharuan dan pengumuman-pengumuman
            mengenai produk-produk, promosi dan pengumuman kami dan untuk
            mengirimkan Anda undangan untuk berpartisipasi dalam program spesial
            kami. Untuk memungkinkan Anda untuk menghubungi dan dihubungi oleh
            pengguna lainnya melalui Situs, sebagaimana diijinkan oleh Situs
            yang berlaku. Untuk mengizinkan Anda untuk berpartisipasi dalam
            papan pesan, obrolan, halaman profil dan blog dan layanan lainnya
            yang mana Anda dapat memasukan informasi dan materi (termasuk
            Halaman Jejaring Sosial kami). Untuk tujuan usaha kami, seperti
            analisis dan pengelolaan usaha kami, penelitian pasar, audit,
            pengembangan produk baru, peningkatan Situs kami, peningkatan produk
            dan layanan kami, mengidentifikasikan tren penggunaan, menentukan
            efektifitas kampanye promosi kami, menyesuaikan pengalaman dan
            konten Situs berdasarkan kegiatan Anda sebelumnya pada Situs, dan
            mengukur kepuasan pelanggan dan menyediakan layanan pelanggan
            (termasuk pemecahan masalah sehubungan dengan masalah-masalah
            pelanggan). Kami menggunakan informasi yang dikumpulkan melalui
            browser atau perangkat Anda untuk tujuan statistikal dan juga untuk
            memastikan bahwa Situs berfungsi dengan benar. Untuk informasi
            detail tentang tujuan-tujuan yang mana kami menggunakan cookies,
            Anda dapat melihat kebijakan cookies kami. Kami dapat menggunakan
            lokasi fisik perangkat Anda untuk memberikan Anda jasa dan konten
            yang telah di personalisasi berdasarkan lokasi. Kami dapat juga
            membagikan lokasi fisik perangkat Anda, dikombinasikan dengan
            informasi mengenai iklan-iklan apa saja yang telah Anda lihat dan
            informasi lainnya yang kami kumpulkan, dengan mitra pemasaran kami
            untuk dapat memungkinkan mereka untuk memberikan Anda dengan content
            yang lebih dipersonalisasi dan untuk mempelajari kePandai Appektifan
            kampanye periklanan. Sebagaimana yang kami anggap perlu atau pantas:
            (a) berdasarkan hukum yang berlaku, termasuk hukum-hukum di luar
            negara tempat tinggal; (b) untuk patuh dengan proses hukum; (c)
            untuk merespon permintaan dari otoritas publik dan pemerintah
            termasuk otoritas publik dan pemerintah di luar negara tempat
            tinggal; (d) untuk melaksanakan syarat dan ketentuan kami; (e) untuk
            melindungi kegiatan operasional kami atau salah satu afiliasi kami;
            (f) untuk melindungi hak-hak, privasi, keselamatan atau properti,
            dan/atau dari afiliasi kami, Anda atau lainnya; dan (g) untuk
            memungkinkan kami untuk mengejar upaya hukum yang tersedia atau
            membatasi kerusakan yang dapat kami pertahankan. KEAMANAN Kami
            menggunakan langkah-langkah organisasional, teknis dan administratif
            yang layak untuk melindungi Informasi Pribadi di bawah kendali kami.
            Sayangnya, tidak ada transmisi data melalui internet atau sistem
            penyimpanan data yang keamanannya terjamin 100%. Jika Anda memiliki
            alasan untuk percaya bahwa interaksi Anda dengan kami tidak lagi
            aman (sebagai contoh, jika Anda merasa bahwa keamanan akun yang Anda
            miliki terganggu), mohon agar segera memberitahukan masalah tersebut
            kepada kami dengan menghubungi kami sesuai dengan formulir bagian
            “Contact Us". AKSES, MODIFIKASI DAN PILIHAN Kami memberikan Anda
            banyak pilihan mengenai penggunaan dan pengungkapan oleh kami atas
            Informasi Pribadi Anda untuk tujuan pemasaran. Kami tidak akan
            mengungkapkan Informasi Pribadi Anda kepada pihak ketiga, untuk
            tujuan pemasaran langsung oleh pihak ketiga apabila kami telah
            menerima dan memproses permintaan dari Anda bahwa Informasi Pribadi
            Anda tidak akan dibagikan kepada pihak ketiga untuk tujuan tersebut.
            Jika Anda ingin mengirimkan permintaan tersebut, silahkan
            memberitahukan kami dengan menggunakan formulir "Contact Us". Mohon
            untuk secara jelas mengindikasikan permintaan Anda bahwa Anda tidak
            ingin agar Informasi Pribadi Anda diungkapkan kepada anak perusahaan
            kami dan/atau pihak ketiga lainnya untuk tujuan pemasaran langsung.
            Untuk meninjau, mengkoreksi, membaharui, merahasiakan, menghapus
            atau membatasi penggunaan Informasi Pribadi Anda oleh kami yang
            sebelumnya telah diberikan kepada kami, silahkan gunakan formulir
            "Contact Us" dan mohon dengan jelas untuk menerangkan permintaan
            Anda. Dalam permintaan Anda, mohon untuk dijelaskan informasi apa
            yang ingin Anda ubah, dirahasiakan dari database kami atau dibiarkan
            untuk diketahui oleh kami dengan batasan apa yang ingin Anda berikan
            atas penggunaan Informasi Pribadi Anda. Kami akan berusaha untuk
            memenuhi permintaan Anda sesegera mungkin. Mohon untuk diperhatikan
            bahwa meskipun kami telah berupaya, bisa saja ada sisa informasi dan
            catatan lainnya yang akan tetap berada dalam database kami, yang
            tidak akan dihapus ataupun diubah. Selanjutnya, perlu diketahui
            bahwa kami mungkin perlu untuk mempertahankan informasi tertentu
            untuk tujuan pencatatan dan/atau untuk penyelesaian transaksi yang
            telah Anda mulai sebelum permintaan atas perubahan atau penghapusan
            (misalnya, ketika Anda melakukan pembelian atau mengikuti suatu
            promosi, Anda bisa saja tidak dapat mengubah atau menghapus
            Informasi Pribadi yang diberikan sampai setelah selesainya pembelian
            atau promosi tersebut). SITUS PIHAK KETIGA Kebijakan Privasi ini
            tidak membahas, dan kami tidak bertanggung jawab atas, privasi,
            informasi atau praktek-praktek lainnya dari pihak ketiga, termasuk
            pihak ketiga yang beroperasi pada situs apapun yang mana pada Situs
            Pandai App terdapat link atas situs tersebut. Dimasukkannya link
            tersebut pada Situs Pandai App tidak berarti menunjukan dukungan
            atas situs terkait oleh kami dan afiliasi kami. Selain itu, kami
            dapat memberikan Anda akses kepada pihak ketiga yang memungkinkan
            Anda untuk mengirim konten ke akun jejaring sosial. Mohon dicatat
            bahwa setiap informasi yang Anda berikan melalui penggunaan fungsi
            ini diatur oleh kebijakan privasi pihak ketiga yang berlaku, dan
            bukan oleh Kebijakan Privasi ini. Kami tidak memiliki kendali, dan
            tidak bertanggung jawab atas, penggunaan pihak ketiga manapun atas
            informasi yang Anda berikan melalui penggunaan fungsi ini. Kami juga
            tidak bertanggung jawab atas pengumpulan, penggunaan dan
            pengungkapan kebijakan dan praktek (termasuk praktek keamanan data)
            dari organisasi lain, seperti Facebook, Apple, Google, Microsoft,
            RIM atau pengembang aplikasi, penyedia platform jejaring sosial,
            penyedia sistem operasi, penyedia layanan nirkabel atau pabrikan
            perangkat lainnya, termasuk Informasi Pribadi yang Anda ungkapkan
            kepada organisasi lainnya melalui atau sehubungan dengan Aplikasi
            atau Halaman Jejaring Sosial kami. PERIODE RETENSI Kami akan
            mempertahankan Informasi Pribadi Anda untuk periode yang diperlukan
            untuk memenuhi tujuan yang diatur dalam Kebijakan Privasi ini dan
            sesuai dengan peraturan perundang-undangan yang berlaku. INFORMASI
            SENSITIF Kami secara umum meminta Anda untuk tidak mengirimkan
            kepada kami, dan agar Anda tidak mengungkapkan, Informasi Pribadi
            yang sensitif (misalnya, informasi yang terkait dengan asal-usul ras
            atau etnis, pandangan politik, agama atau kepercayaan lainnya,
            kesehatan atau kondisi medis, latar belakang kriminal atau
            keanggotaan serikat buruh) pada atau melalui Situs atau kepada kami.
            Dalam pengecualian tertentu, seperti permintaan asuransi, kami akan
            menjelaskan kepada Anda bagaimana Anda dapat melakukan hal ini
            secara aman. PEMBARUAN ATAS KEBIJAKAN PRIVASI INI Kami dapat
            mengubah Kebijakan Privasi ini. Mohon untuk dilihat tulisan "Update
            Terakhir" pada bagian atas halaman ini untuk melihat kapan terakhir
            Kebijakan Privasi ini terakhir direvisi. Setiap perubahan atas
            Kebijakan Privasi ini akan menjadi efektif saat kami memasukan
            revisi Kebijakan Privasi ini pada Situs. HUBUNGI KAMI Apabila Anda
            memiliki pertanyaan mengenai Kebijakan Privasi ini, mohon untuk
            menghubungi kami melalui e-mail support@pandaiapp.com
          </p>
        </div>
      </main>
      <footer className={styles.footer}>
        <p>Powered by Pandai App</p>
      </footer>
    </div>
  )
}
